### ISSUE TITLE
Make no_std compatible

### ISSUE THREAD

**Issue by atsyplenkov** [atsyplenkov/qbin#13]
Add to CI smth like

```
  no-std-build:
    name: Make sure the code is no-std compatible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup update stable && rustup target add thumbv7em-none-eabihf
      - run: cargo build --target=thumbv7em-none-eabihf --no-default-features

```

Add in `cargo.toml`:
```
[features]
default = ["std"]
std = [
    "geo/std",
    "either/std",
    "i_tree/std",
    "i_key_sort/std",
    "robust/std",
]

[dependencies]
geo = { version = "...", default-features = false }
either = { version = "1.15.0", default-features = false }
i_tree = { version = "0.8.3", default-features = false }
i_key_sort = { version = "0.2.0", default-features = false }
robust = { version = "1.1.0", default-features = false }

```
